server:
  port: 8081
  mode: development

database:
  host: 192.168.58.102
  port: 5432
  user: user_rbc3B8
  password: password_DfA4Pw
  dbname: hcp_server
  sslmode: disable

redis:
  addr: 192.168.58.102:6379
  password: redis_ttEreS
  db: 0

log:
  level: debug
